### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by sd2020bs** [mimicmobile/flask-telegram-relay-bot#2]
When alert is generated by alertmanager, i receive email amd message to telegram.
In email i have full log with problem, but in telegram i have only this:
Failed to send via Flask to Telegram!

I tried make curl:
curl -k -X POST -d '{"message": "hello" }' http://127.0.0.1:9119/alert

And get this message too: Failed to send via Flask to Telegram!
in logs:

INFO:__main__:None
DEBUG:telegram.bot:Entering: send_message
DEBUG:telegram.vendor.ptb_urllib3.urllib3.connectionpool:https://api.telegram.org:443 "POST /botxxxxxxxxxxxxxx/sendMessage HTTP/1.1" 200 172
DEBUG:telegram.bot:{'delete_chat_photo': False, 'new_chat_photo': [], 'text': u'Failed to send via Flask to Telegram!', 'channel_chat_created': False, 'caption_entities': [], 'entities': [],
 'new_chat_members': [], 'supergroup_chat_created': False, 'chat': {'type': u'channel', 'id': -1001xxxxxxxx, 'title': u'alertmgr_qx'}, 'photo': [], 'date': 1558686604, 'group_chat_created':
 False, 'message_id': 102}
DEBUG:telegram.bot:Exiting: send_message
INFO:werkzeug:127.0.0.1 - - [24/May/2019 08:30:04] "POST /alert HTTP/1.1" 200 -

**Comment by corcoran** [comment]
This looks like an issue with alertmanager and has nothing to do with flask-telegram-relay-bot.
